[versions]
postgresql = "42.7.7"
jooq = "3.20.2"
hikari-cp = "6.3.0"
flyway-postgres = "11.9.1"
slf4j = "2.0.16"
logback = "1.5.8"
coroutines-core = "1.8.1"


[libraries]
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari-cp" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway-postgres" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-core"}

[bundles]
database = ["postgresql", "hikari-cp", "flyway-postgres"]
logging = ["slf4j-api", "logback"]